# Generated by Django 3.0.7 on 2020-07-29 22:19

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userface', '0004_auto_20200629_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plateNum',
            field=models.CharField(default=' ', max_length=6),
        ),

    ]
